# Generated by Django 6.0.5 on 2026-05-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'deposit'), ('WITHDRAW', 'withdraw')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='pin',
            field=models.CharField(),
        ),
    ]
